#====================================================================================================#
#                                           EUREKA SERVER - INFO                                     #
#====================================================================================================#
eureka:
  instance:
    hostname: ${HOST_NAME:localhost}
  client:
    fetch-registry: ${FETCH_REGISTRY:true}
    register-with-eureka: ${REGISTER_WITH_EUREKA:true}
    service-url: 
      defaultZone: ${SERVICE_URL:http://${eureka.instance.hostname}:8761/eureka/}
      

